version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
      nodejs: 12
  build:
    commands:
      - composer install
      - npm install
      - npm run prod
      - rm -rf node_modules
      - vendor/bin/phpunit --log-junit /tmp/phpunit-log.xml
reports:
  SurefireReports:
    files:
      - 'phpunit-log.xml'
    base-directory: '/tmp'
    file-format: JunitXml
artifacts:
  files:
    - '**/*'
